layout_spectrum: 1
name: Teacherkiat
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
color:
  brandStrength: 0.846543
  lightness: 0.7925801
  saturation: 0.7251265
  rhythmicContrast: 0.8086004
  brandColors:
    - '#000101'
typography_spectrum: 0.4055649
